### ISSUE TITLE
The plugin doesn't work when the server is launching

### ISSUE THREAD

**Issue by Sparryx** [pashavoid/ReputationPlus#1]
> [16:53:49] [Server thread/ERROR]: Could not load 'plugins/ReputationPlus (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: ru/pashavoid/reputationplus/ReputationPlus has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[server.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[server.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[server.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:383) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:183) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-2740d5a-890130b]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.UnsupportedClassVersionError: ru/pashavoid/reputationplus/ReputationPlus has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_252]
at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_252]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_252]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[server.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[server.jar:git-Spigot-2740d5a-890130b]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_252]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_252]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-2740d5a-890130b]
... 7 more

**Comment by pashavoid** [comment]
Hmm, interesting. I used the latest version of the JDK, and you are using 8. I will Recompile it and it will run in the next update.
